name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: install lftp
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y lftp

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        run: lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .*/ --reverse --verbose --delete public/ $DESTINATION_FOLDER; bye"
        env: FTP_HOST = ${{ secrets.FTP_HOST }}
          FTP_USERNAME = ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD = ${{ secrets.FTP_PASSWORD }}
          DESTINATION_FOLDER = ${{ secrets.DESTINATION_FOLDER }}
